blank_issues_enabled: false
contact_links:
  - name: Need a place to start? Try the Knowledge Base!
    url: https://knowledgebase.pi-top.com/
    about: Find answers to commonly asked questions.
  - name: Need to go a little deeper? Try the Forum!
    url: https://forum.pi-top.com/c/pi-top-software
    about: Discuss and search through support topics.
  - name: Committed to creating a GitHub Issue? Read the Wiki!
    url: https://github.com/pi-top/pi-top-Python-SDK/wiki/
    about: Get information about how to create effective GitHub Issues.
  - name: Looking to learn about programming? Check out Further!
    url: https://further.pi-top.com/explore/
    about: Complete challenges to learn how to program your pi-top.
