name: Track and Report on Python Application Timing and Complexity

on:
  pull_request:
  push:

jobs:
  wily:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2-beta
        with:
          fetch-depth: 0

      - uses: actions/checkout@v2-beta
        with:
          ref: refs/heads/master
          clean: false

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install wily

      - name: Build wily
        run: |
          wily build generator/ test/ .
          wily diff generator/ -r master

      - name: Show wily report
        run: |
          wily report generator/generator.py
          wily report test/test_generator.py

      - name: Show wily rank
        run: |
          wily rank generator/
          wily rank test/
          wily rank .
